#!/usr/bin/env python3
"""
OceanBase CE Memory System - Schema Loader and Validator

Loads, validates, and applies the database schema to OceanBase CE 4.x.
Supports both full deployment and dry-run verification modes.

Usage:
    # Apply schema (creates all tables)
    python3 schema_loader.py --apply
    
    # Dry run (verify without applying)
    python3 schema_loader.py --dry-run
    
    # Check if schema exists (status check)
    python3 schema_loader.py --check
"""

import sys
import os
from typing import Dict, List, Any


# Database connection configuration
DB_CONFIG = {
    'host': os.environ.get('OB_HOST', 'localhost'),
    'port': int(os.environ.get('OB_PORT', 2881)),
    'user': os.environ.get('OB_USER', 'root@sys'),
    'password': os.environ.get('OB_PASS', ''),
}


# Schema SQL statements (from SKILL.md)
SCHEMA_DDL = """
-- Core Memory Tables

CREATE TABLE IF NOT EXISTS memory_nodes (
    node_id      BIGINT PRIMARY KEY,
    label        VARCHAR(256),
    node_type    VARCHAR(100),
    properties   TEXT,
    embedding    TEXT,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX idx_nodes_type ON memory_nodes(node_type);
CREATE INDEX idx_nodes_label ON memory_nodes(label);

-- Memory Edges (Graph Relationships)

CREATE TABLE IF NOT EXISTS memory_edges (
    edge_id      BIGINT PRIMARY KEY,
    source_node  BIGINT NOT NULL REFERENCES memory_nodes(node_id),
    target_node  BIGINT NOT NULL REFERENCES memory_nodes(node_id),
    edge_type    VARCHAR(200),
    properties   TEXT,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_edges_source ON memory_edges(source_node);
CREATE INDEX idx_edges_target ON memory_edges(target_node);
CREATE INDEX idx_edges_type ON memory_edges(edge_type);

-- Core Memory Items

CREATE TABLE IF NOT EXISTS memories (
    id           BIGINT PRIMARY KEY,
    content      TEXT,
    memory_type  VARCHAR(100),
    category     VARCHAR(100),
    priority     INT DEFAULT 2 CHECK(priority BETWEEN 1 AND 3),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    expires_at   TIMESTAMP NULL
);

CREATE INDEX idx_memories_category ON memories(category);
CREATE INDEX idx_memories_type ON memories(memory_type);
CREATE INDEX idx_memories_priority ON memories(priority);

-- Memory Embeddings

CREATE TABLE IF NOT EXISTS memories_vectors (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id    BIGINT NOT NULL REFERENCES memories(id) ON DELETE CASCADE,
    embedding    TEXT,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    model_version VARCHAR(50) DEFAULT 'bge-m3',
    dimensions   INT DEFAULT 1024
);

CREATE INDEX idx_vectors_memory ON memories_vectors(memory_id);
"""

# JSON Decomposition Relationship Tables (v0.1.0 Application-Layer Pattern)
DECOMPOSITION_DDL = """
-- Node properties (decomposed from memory_nodes.properties)
CREATE TABLE IF NOT EXISTS memory_node_properties (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id      BIGINT NOT NULL REFERENCES memory_nodes(node_id),
    property_name VARCHAR(100) NOT NULL,
    property_value TEXT,
    property_type VARCHAR(50),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_node_props_node ON memory_node_properties(node_id);

-- Edge properties (decomposed from memory_edges.properties)
CREATE TABLE IF NOT EXISTS memory_edge_properties (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edge_id      BIGINT NOT NULL REFERENCES memory_edges(edge_id),
    property_name VARCHAR(100) NOT NULL,
    property_value TEXT,
    property_type VARCHAR(50),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_edge_props_edge ON memory_edge_properties(edge_id);

-- Memory content fields (decomposed from memories.content)
CREATE TABLE IF NOT EXISTS memory_content_fields (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id    BIGINT NOT NULL REFERENCES memories(id),
    field_name   VARCHAR(100),
    field_value  TEXT,
    field_type   VARCHAR(50),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_content_fields_mem ON memory_content_fields(memory_id);

-- Memory tag items (decomposed from stored tags)
CREATE TABLE IF NOT EXISTS memory_tag_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id    BIGINT NOT NULL REFERENCES memories(id),
    tag_name     VARCHAR(100),
    tag_value    VARCHAR(500),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tag_items_mem ON memory_tag_items(memory_id);

-- Memory metadata fields (decomposed from stored metadata)
CREATE TABLE IF NOT EXISTS memory_metadata_fields (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id    BIGINT NOT NULL REFERENCES memories(id),
    field_name   VARCHAR(100),
    field_value  TEXT,
    field_type   VARCHAR(50),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_meta_fields_mem ON memory_metadata_fields(memory_id);

-- Memory relationships (graph-like between memories)
CREATE TABLE IF NOT EXISTS memory_relationships (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_memory_id BIGINT NOT NULL REFERENCES memory_nodes(node_id),
    target_memory_id BIGINT NOT NULL REFERENCES memory_nodes(node_id),
    relationship_type VARCHAR(100),
    confidence    FLOAT DEFAULT 1.0 CHECK(confidence >= 0 AND confidence <= 1),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_memory_id, target_memory_id, relationship_type)
);

CREATE INDEX idx_relationships_source ON memory_relationships(source_memory_id);
CREATE INDEX idx_relationships_target ON memory_relationships(target_memory_id);
CREATE INDEX idx_relationships_type ON memory_relationships(relationship_type);
"""


class SchemaLoader:
    def __init__(self, host=None, port=None, user=None, password=None):
        self.config = DB_CONFIG.copy()
        if host:
            self.config['host'] = host
        if port:
            self.config['port'] = port
        if user:
            self.config['user'] = user
        if password:
            self.config['password'] = password
    
    def get_connection_string(self) -> str:
        return f"obclient -h{self.config['host']} -P{self.config['port']} " \
               f"-u{self.config['user']} -p{self.config['password']}"
    
    def execute_sql(self, sql: str, dry_run: bool = False) -> Dict[str, Any]:
        """Execute SQL statement via obclient."""
        if dry_run:
            print(f"[DRY RUN] Would execute:\n{sql}\n")
            return {'success': True, 'dry_run': True}
        
        cmd = f"{self.get_connection_string()} -e \"{sql}\""
        
        try:
            import subprocess
            result = subprocess.run(
                cmd.split(),
                capture_output=True,
                text=True,
                timeout=30
            )
            
            return {
                'success': result.returncode == 0,
                'output': result.stdout.strip() if result.stdout else '',
                'error': result.stderr.strip() if result.stderr else ''
            }
        except Exception as e:
            return {'success': False, 'error': str(e)}
    
    def check_schema_exists(self) -> Dict[str, bool]:
        """Check which tables already exist in the database."""
        print("Checking existing schema...")
        
        tables = [
            'memory_nodes', 'memory_edges', 'memories', 'memories_vectors',
            'memory_node_properties', 'memory_edge_properties',
            'memory_content_fields', 'memory_tag_items',
            'memory_metadata_fields', 'memory_relationships'
        ]
        
        results = {}
        for table in tables:
            sql = f"SHOW TABLES LIKE '{table}'"
            result = self.execute_sql(sql)
            exists = len(result.get('output', '')) > 0
            results[table] = exists
            
        return results
    
    def apply_schema(self, dry_run: bool = False):
        """Apply the complete schema to OceanBase CE."""
        print("=" * 60)
        print("OceanBase CE Memory System Schema Loader")
        print("=" * 60)
        
        if dry_run:
            print("\n⚠️  DRY RUN MODE - No changes will be applied\n")
        
        # Check current schema status
        existing = self.check_schema_exists()
        missing_tables = [t for t, exists in existing.items() if not exists]
        
        if not dry_run and not missing_tables:
            print("✓ All tables already exist. Nothing to do.")
            return
        
        # Apply core schema
        print("\nApplying core schema...")
        result = self.execute_sql(SCHEMA_DDL, dry_run)
        if not result['success']:
            print(f"✗ Error applying core schema: {result.get('error', '')}")
            return False
        
        print("✓ Core schema applied successfully.")
        
        # Apply decomposition tables (v0.1.0)
        print("\nApplying v0.1.0 decomposition relationship tables...")
        result = self.execute_sql(DECOMPOSITION_DDL, dry_run)
        if not result['success']:
            print(f"✗ Error applying decomposition tables: {result.get('error', '')}")
            return False
        
        print("✓ Decomposition tables applied successfully.")
        
        # Verify deployment
        if not dry_run:
            new_status = self.check_schema_exists()
            all_exist = all(new_status.values())
            
            print("\n" + "=" * 60)
            if all_exist:
                print("✓ Schema deployment completed successfully!")
                return True
            else:
                failed = [t for t, exists in new_status.items() if not exists]
                print(f"✗ Some tables failed to create: {', '.join(failed)}")
                return False
        
        return True


def main():
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Load and validate OceanBase CE Memory System schema'
    )
    parser.add_argument('--apply', action='store_true', help='Apply schema to database')
    parser.add_argument('--dry-run', action='store_true', help='Verify without applying')
    parser.add_argument('--check', action='store_true', help='Check existing schema status')
    parser.add_argument('--host', type=str, help='OceanBase host address')
    parser.add_argument('--port', type=int, help='OceanBase port (default: 2881)')
    parser.add_argument('--user', type=str, help='OceanBase user@tenant')
    parser.add_argument('--password', type=str, help='OceanBase password')
    
    args = parser.parse_args()
    
    loader = SchemaLoader(
        host=args.host,
        port=args.port,
        user=args.user,
        password=args.password
    )
    
    if args.apply:
        success = loader.apply_schema(dry_run=False)
        sys.exit(0 if success else 1)
    
    elif args.dry_run:
        loader.apply_schema(dry_run=True)
    
    elif args.check:
        status = loader.check_schema_exists()
        
        print("\nSchema Status:")
        print("-" * 40)
        for table, exists in sorted(status.items()):
            status_icon = "✓" if exists else "✗"
            print(f"{status_icon} {table}")
        
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
